/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SpectrumsRouteRouteImport } from './routes/spectrums/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SpectrumsIndexRouteImport } from './routes/spectrums/index'
import { Route as AuthSignupRouteImport } from './routes/auth/signup'
import { Route as AuthLoginRouteImport } from './routes/auth/login'
import { Route as SpectrumsSpectrumIdIndexRouteImport } from './routes/spectrums/$spectrumId/index'

const SpectrumsRouteRoute = SpectrumsRouteRouteImport.update({
  id: '/spectrums',
  path: '/spectrums',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectrumsIndexRoute = SpectrumsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SpectrumsRouteRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SpectrumsSpectrumIdIndexRoute =
  SpectrumsSpectrumIdIndexRouteImport.update({
    id: '/$spectrumId/',
    path: '/$spectrumId/',
    getParentRoute: () => SpectrumsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/spectrums': typeof SpectrumsRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/spectrums/': typeof SpectrumsIndexRoute
  '/spectrums/$spectrumId': typeof SpectrumsSpectrumIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/spectrums': typeof SpectrumsIndexRoute
  '/spectrums/$spectrumId': typeof SpectrumsSpectrumIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/spectrums': typeof SpectrumsRouteRouteWithChildren
  '/auth/login': typeof AuthLoginRoute
  '/auth/signup': typeof AuthSignupRoute
  '/spectrums/': typeof SpectrumsIndexRoute
  '/spectrums/$spectrumId/': typeof SpectrumsSpectrumIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/spectrums'
    | '/auth/login'
    | '/auth/signup'
    | '/spectrums/'
    | '/spectrums/$spectrumId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth/login'
    | '/auth/signup'
    | '/spectrums'
    | '/spectrums/$spectrumId'
  id:
    | '__root__'
    | '/'
    | '/spectrums'
    | '/auth/login'
    | '/auth/signup'
    | '/spectrums/'
    | '/spectrums/$spectrumId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SpectrumsRouteRoute: typeof SpectrumsRouteRouteWithChildren
  AuthLoginRoute: typeof AuthLoginRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/spectrums': {
      id: '/spectrums'
      path: '/spectrums'
      fullPath: '/spectrums'
      preLoaderRoute: typeof SpectrumsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectrums/': {
      id: '/spectrums/'
      path: '/'
      fullPath: '/spectrums/'
      preLoaderRoute: typeof SpectrumsIndexRouteImport
      parentRoute: typeof SpectrumsRouteRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/spectrums/$spectrumId/': {
      id: '/spectrums/$spectrumId/'
      path: '/$spectrumId'
      fullPath: '/spectrums/$spectrumId'
      preLoaderRoute: typeof SpectrumsSpectrumIdIndexRouteImport
      parentRoute: typeof SpectrumsRouteRoute
    }
  }
}

interface SpectrumsRouteRouteChildren {
  SpectrumsIndexRoute: typeof SpectrumsIndexRoute
  SpectrumsSpectrumIdIndexRoute: typeof SpectrumsSpectrumIdIndexRoute
}

const SpectrumsRouteRouteChildren: SpectrumsRouteRouteChildren = {
  SpectrumsIndexRoute: SpectrumsIndexRoute,
  SpectrumsSpectrumIdIndexRoute: SpectrumsSpectrumIdIndexRoute,
}

const SpectrumsRouteRouteWithChildren = SpectrumsRouteRoute._addFileChildren(
  SpectrumsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SpectrumsRouteRoute: SpectrumsRouteRouteWithChildren,
  AuthLoginRoute: AuthLoginRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
