// src/errors/error-codes.ts
export enum ErrorCode {
  // Generic
  UNKNOWN = 'UNKNOWN',
  INTERNAL = 'INTERNAL',
  NOT_FOUND = 'NOT_FOUND',
  BAD_REQUEST = 'BAD_REQUEST',
  UNAUTHORIZED = 'UNAUTHORIZED',
  FORBIDDEN = 'FORBIDDEN',
  CONFLICT = 'CONFLICT',
  UNPROCESSABLE = 'UNPROCESSABLE',
  TOO_MANY_REQUESTS = 'TOO_MANY_REQUESTS',
  SERVICE_UNAVAILABLE = 'SERVICE_UNAVAILABLE',

  // Validation
  VALIDATION_FAILED = 'VALIDATION_FAILED',
  PAYLOAD_TOO_LARGE = 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE = 'UNSUPPORTED_MEDIA_TYPE',

  // Auth/JWT
  TOKEN_INVALID = 'TOKEN_INVALID',
  TOKEN_EXPIRED = 'TOKEN_EXPIRED',

  // Prisma (examples)
  PRISMA_UNIQUE_CONSTRAINT = 'PRISMA_UNIQUE_CONSTRAINT',
  PRISMA_FOREIGN_KEY_CONSTRAINT = 'PRISMA_FOREIGN_KEY_CONSTRAINT',
  PRISMA_NOT_FOUND = 'PRISMA_NOT_FOUND',
  PRISMA_INVALID_FIELD = 'PRISMA_INVALID_FIELD',

  // Uploads
  UPLOAD_ERROR = 'UPLOAD_ERROR',
}
